services:
  hyultisfr:
    image: webhome:latest #use port 3001, I do not use "ports", because that doesn't change the container to container port number, only the external port (and we don't want that)
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ./dynamic:/app/dynamic
      - ./config:/app/config

# external acces from proxy
networks:
  web:
    name: internal_web
