name: publish website
run-name: publish new version on server
on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps: # based on : https://github.com/mohammed-bahumaish/github-actions-push-docker-image-via-ssh/blob/main/.github/workflows/deploy.yaml
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t webhome:latest -f ./docker/image .

      - name: Save Docker image as tar file
        run: docker save -o webhome.tar webhome:latest

      - name: Transfer Docker image to remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -P ${{ secrets.REMOTE_SERVER_PORT }} webhome.tar ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }}:${{ secrets.REMOTE_SERVER_PATH }}

      - name: Load Docker image on remote server
        run: |
          ssh -q -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_SERVER_PORT }} ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          sudo docker load -i ${{ secrets.REMOTE_SERVER_PATH }}/webhome.tar
          ENDSSH

      - name: Transfer Docker Compose file to remote server
        run: |
          scp -o StrictHostKeyChecking=no -P ${{ secrets.REMOTE_SERVER_PORT }} ./docker/docker-compose.yml ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }}:${{ secrets.REMOTE_SERVER_PATH }}

      - name: Deploy Docker containers using Docker Compose on remote server
        run: |
          ssh -q -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_SERVER_PORT }} ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          cd ${{ secrets.REMOTE_SERVER_PATH }}
          rm webhome.tar
          sudo docker compose down
          sudo docker compose up -d
          ENDSSH