name: test ssh server
run-name: test ssh server
on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test connect to distance ssh server
        run: |
          echo ${pwd}
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -q -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_SERVER_PORT }} ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          cd ${{ secrets.REMOTE_SERVER_PATH }}
          touch test.ok
          ENDSSH